name: Push Tags to Destination Repo

on:
  push:
    tags: "*"

jobs:
  push-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Add destination repository as remote
        run: |
          git remote add destination https://github.com/KuyeselaOrganization/test-project-releases.git

      - name: Push tags to destination repository
        run: |
          git fetch --tags destination
          git push destination --tags
