name: Push Tags to Destination Repo

on:
  push:
    tags: "*"

jobs:
  push-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Set up Git for remote repository
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'roychanunkha@gmail.com'

      - name: Add destination repository as remote
        run: |
          git remote add destination https://github.com/HISMalawi/test-project-releases/

      - name: Push tags to destination repository
        run: |
          git fetch --tags destination
          git push destination --tags
